import type { Artikel, Template, Praktijkcase, Nieuwsbericht, Event, Thema } from '@/types/content'

export const DUMMY_THEMAS: Thema[] = [
  { _id: 't1', title: 'Financiën & Control',      slug: 'financien-control',      beschrijving: 'Begrotingsproces, jaarrekening, rechtmatigheid en financieel beheer.', kleur: '#154273', artikelCount: 14 },
  { _id: 't2', title: 'HRM & Organisatie',         slug: 'hrm-organisatie',         beschrijving: 'Personeelsbeleid, werving & selectie, organisatieontwikkeling.',       kleur: '#007BC7', artikelCount: 11 },
  { _id: 't3', title: 'Inkoop & Aanbesteding',     slug: 'inkoop-aanbesteding',     beschrijving: 'Europees aanbesteden, inkoopbeleid, contractmanagement.',               kleur: '#F9A800', artikelCount: 9  },
  { _id: 't4', title: 'Informatiemanagement',      slug: 'informatiemanagement',    beschrijving: 'Informatiearchitectuur, data governance, digitale transformatie.',     kleur: '#39870C', artikelCount: 17 },
  { _id: 't5', title: 'Juridische Zaken',          slug: 'juridische-zaken',        beschrijving: 'Regelgeving, bezwaar & beroep, privacy (AVG) en juridisch advies.',    kleur: '#E17000', artikelCount: 8  },
  { _id: 't6', title: 'Communicatie & Participatie', slug: 'communicatie-participatie', beschrijving: 'Burgerparticipatie, interne communicatie en publieksvoorlichting.',  kleur: '#42145F', artikelCount: 6  },
]

export const DUMMY_ARTIKELEN: Artikel[] = [
  {
    _id: 'a1', _type: 'artikel',
    titel: 'Rechtmatigheidsverantwoording 2024: wat verandert er voor gemeenten?',
    slug: 'rechtmatigheidsverantwoording-2024',
    samenvatting: 'Vanaf boekjaar 2023 legt het college zelf verantwoording af over de rechtmatigheid. Deze handreiking beschrijft de stappen en aandachtspunten voor gemeenten.',
    tldr: 'Het college geeft voortaan zelf een rechtmatigheidsverklaring af in de jaarrekening. De accountant toetst deze, maar schrijft geen afzonderlijk oordeel meer.',
    body: [], leestijd: 8,
    themas: [DUMMY_THEMAS[0]],
    doelgroepen: ['gemeente'],
    tags: ['rechtmatigheid', 'jaarrekening', 'BBV', 'accountant'],
    status: 'published',
    gepubliceerdOp: '2024-03-15T10:00:00Z',
    bijgewerktOp: '2024-04-01T08:00:00Z',
    reviewStatus: 'ok',
    eigenaar: 'Werkgroep Financiën',
  },
  {
    _id: 'a2', _type: 'artikel',
    titel: 'Introductie Common Ground: wat betekent het voor uw organisatie?',
    slug: 'introductie-common-ground',
    samenvatting: 'Common Ground verandert de informatiehuishouding van gemeenten fundamenteel. Dit artikel legt het principe uit en geeft concrete handvatten voor implementatie.',
    tldr: 'Common Ground = data bij de bron. Minder kopieën, meer actuele gegevens, betere dienstverlening.',
    body: [], leestijd: 12,
    themas: [DUMMY_THEMAS[3]],
    doelgroepen: ['gemeente', 'uitvoeringsorganisatie'],
    tags: ['Common Ground', 'architectuur', 'digitalisering', 'API'],
    status: 'published',
    gepubliceerdOp: '2024-02-20T09:00:00Z',
    bijgewerktOp: '2024-02-20T09:00:00Z',
    reviewStatus: 'ok',
    eigenaar: 'Werkgroep Informatiemanagement',
  },
  {
    _id: 'a3', _type: 'artikel',
    titel: 'Duurzaam inkopen: Europese verplichtingen en praktische aanpak',
    slug: 'duurzaam-inkopen-europese-verplichtingen',
    samenvatting: 'De Europese duurzaamheidsvereisten voor overheidsopdrachten worden aangescherpt. Lees hier wat dat betekent voor uw inkoopbeleid en hoe u hierop voorbereidt.',
    body: [], leestijd: 10,
    themas: [DUMMY_THEMAS[2]],
    doelgroepen: ['gemeente', 'provincie', 'rijksoverheid'],
    tags: ['inkoop', 'duurzaamheid', 'Europees', 'MVO'],
    status: 'published',
    gepubliceerdOp: '2024-01-10T11:00:00Z',
    bijgewerktOp: '2024-01-15T11:00:00Z',
    reviewStatus: 'ok',
    eigenaar: 'Werkgroep Inkoop',
  },
  {
    _id: 'a4', _type: 'artikel',
    titel: 'Hybride werken en de gevolgen voor het HRM-beleid',
    slug: 'hybride-werken-hrm-beleid',
    samenvatting: 'Hybride werken is de norm geworden. Maar welke aanpassingen vraagt dit van uw arbeidsvoorwaardenbeleid, verzuimbeleid en leiderschapsontwikkeling?',
    body: [], leestijd: 7,
    themas: [DUMMY_THEMAS[1]],
    doelgroepen: ['gemeente', 'provincie', 'waterschap'],
    tags: ['hybride werken', 'HRM', 'arbeidsvoorwaarden', 'welzijn'],
    status: 'published',
    gepubliceerdOp: '2024-01-05T09:00:00Z',
    bijgewerktOp: '2024-01-05T09:00:00Z',
    reviewStatus: 'ok',
    eigenaar: 'Werkgroep HRM',
  },
]

export const DUMMY_TEMPLATES: Template[] = [
  {
    _id: 'tp1', _type: 'template',
    titel: 'Checklist Rechtmatigheidsverantwoording',
    slug: 'checklist-rechtmatigheidsverantwoording',
    samenvatting: 'Stap-voor-stap checklist voor het opstellen van de rechtmatigheidsverantwoording in de jaarrekening.',
    themas: [DUMMY_THEMAS[0]], doelgroepen: ['gemeente'],
    bijlagen: [{ _key: 'b1', titel: 'Checklist RV 2024.xlsx', bestandstype: 'xlsx', bestandsgrootte: 45000, asset: { _ref: '', _type: 'reference' } }],
    tags: ['checklist', 'rechtmatigheid', 'jaarrekening'],
    bestandstype: 'xlsx', status: 'published',
    gepubliceerdOp: '2024-02-01T10:00:00Z',
    bijgewerktOp: '2024-02-01T10:00:00Z',
    eigenaar: 'Werkgroep Financiën',
  },
  {
    _id: 'tp2', _type: 'template',
    titel: 'Model Inkoopbeleid Gemeente',
    slug: 'model-inkoopbeleid-gemeente',
    samenvatting: 'Volledig inkoopbeleidsdocument inclusief drempelwaarden, selectiecriteria en duurzaamheidsvereisten. Aanpasbaar naar gemeentegrootte.',
    themas: [DUMMY_THEMAS[2]], doelgroepen: ['gemeente'],
    bijlagen: [{ _key: 'b2', titel: 'Model Inkoopbeleid 2024.docx', bestandstype: 'docx', bestandsgrootte: 120000, asset: { _ref: '', _type: 'reference' } }],
    tags: ['inkoopbeleid', 'model', 'aanbesteding'],
    bestandstype: 'docx', status: 'published',
    gepubliceerdOp: '2023-12-01T10:00:00Z',
    bijgewerktOp: '2024-01-10T10:00:00Z',
    eigenaar: 'Werkgroep Inkoop',
  },
]

export const DUMMY_CASES: Praktijkcase[] = [
  {
    _id: 'c1', _type: 'praktijkcase',
    titel: 'Gemeente Ede: van papier naar digitaal contractbeheer in 6 maanden',
    slug: 'ede-digitaal-contractbeheer',
    samenvatting: 'Hoe gemeente Ede haar contractbeheer volledig digitaliseerde, grip kreeg op contractvervaldatums en €200.000 bespaarde op stilzwijgende verlengingen.',
    themas: [DUMMY_THEMAS[2]],
    doelgroepen: ['gemeente'],
    tags: ['contractbeheer', 'digitalisering', 'inkoop', 'besparing'],
    status: 'published',
    gepubliceerdOp: '2024-03-01T10:00:00Z',
    bijgewerktOp: '2024-03-01T10:00:00Z',
  },
  {
    _id: 'c2', _type: 'praktijkcase',
    titel: 'Waterschap Rivierenland: AVG-implementatie in 12 stappen',
    slug: 'waterschap-rivierenland-avg-implementatie',
    samenvatting: 'Waterschap Rivierenland deelt hoe zij de AVG-implementatie pragmatisch aanpakten: van register van verwerkingsactiviteiten tot bewustwordingsprogramma voor medewerkers.',
    themas: [DUMMY_THEMAS[4]],
    doelgroepen: ['waterschap', 'gemeente'],
    tags: ['AVG', 'privacy', 'implementatie', 'bewustwording'],
    status: 'published',
    gepubliceerdOp: '2024-02-10T10:00:00Z',
    bijgewerktOp: '2024-02-10T10:00:00Z',
  },
]

export const DUMMY_NIEUWS: Nieuwsbericht[] = [
  {
    _id: 'n1', _type: 'nieuws',
    titel: 'Nieuwe handreiking "Grip op Gemeenschappelijke Regelingen" gepubliceerd',
    slug: 'handreiking-grip-op-gemeenschappelijke-regelingen',
    samenvatting: 'KBO publiceert een uitgebreide handreiking voor gemeenten over governance en verantwoording bij deelname in gemeenschappelijke regelingen.',
    body: [],
    themas: [DUMMY_THEMAS[0]], tags: ['GR', 'governance', 'samenwerking'],
    status: 'published',
    gepubliceerdOp: '2024-04-05T09:00:00Z',
    bijgewerktOp: '2024-04-05T09:00:00Z',
  },
  {
    _id: 'n2', _type: 'nieuws',
    titel: 'KBO lanceert nieuwe Community rondom Inkoop & Aanbesteding',
    slug: 'kbo-community-inkoop-aanbesteding',
    samenvatting: 'Professionals op het gebied van inkoop en aanbesteding kunnen voortaan ervaringen uitwisselen via de nieuwe KBO Community. Aanmelden kan via de website.',
    body: [],
    themas: [DUMMY_THEMAS[2]], tags: ['community', 'inkoop', 'netwerk'],
    status: 'published',
    gepubliceerdOp: '2024-03-20T10:00:00Z',
    bijgewerktOp: '2024-03-20T10:00:00Z',
  },
  {
    _id: 'n3', _type: 'nieuws',
    titel: 'Resultaten benchmark "Overhead bij Gemeenten 2023" beschikbaar',
    slug: 'benchmark-overhead-gemeenten-2023',
    samenvatting: 'De jaarlijkse benchmark overhead bij gemeenten is gepubliceerd. Gemeenten met meer dan 50.000 inwoners scoren gemiddeld 16,8% overhead — een lichte daling ten opzichte van 2022.',
    body: [],
    themas: [DUMMY_THEMAS[0], DUMMY_THEMAS[1]], tags: ['benchmark', 'overhead', 'benchmark'],
    status: 'published',
    gepubliceerdOp: '2024-03-01T10:00:00Z',
    bijgewerktOp: '2024-03-01T10:00:00Z',
  },
]

export const DUMMY_EVENTS: Event[] = [
  {
    _id: 'e1', _type: 'event',
    titel: 'Masterclass Rechtmatigheidsverantwoording — Wat u moet weten',
    slug: 'masterclass-rechtmatigheidsverantwoording-2024',
    samenvatting: 'Interactieve online masterclass over de rechtmatigheidsverantwoording. Specifiek gericht op financieel controllers en gemeentesecretarissen.',
    startdatum: '2024-06-12', starttijd: '13:00', eindtijd: '16:00',
    locatie: 'Online (Teams)',
    online: true,
    aanmeldUrl: '#',
    themas: [DUMMY_THEMAS[0]], doelgroepen: ['gemeente'],
    tags: ['masterclass', 'rechtmatigheid', 'online'],
    status: 'published',
    gepubliceerdOp: '2024-04-01T10:00:00Z',
  },
  {
    _id: 'e2', _type: 'event',
    titel: 'KBO Jaarcongres 2024 — Bedrijfsvoering in Beweging',
    slug: 'kbo-jaarcongres-2024',
    samenvatting: 'Het jaarlijkse KBO-congres brengt meer dan 400 professionals uit de overheid samen. Dit jaar met als thema "Bedrijfsvoering in Beweging: van control naar regie".',
    startdatum: '2024-09-26',
    locatie: 'Werkspoorkathedraal, Utrecht',
    online: false,
    aanmeldUrl: '#',
    themas: [DUMMY_THEMAS[0], DUMMY_THEMAS[1], DUMMY_THEMAS[3]],
    doelgroepen: ['gemeente', 'provincie', 'waterschap', 'rijksoverheid'],
    tags: ['congres', 'netwerk', 'jaarcongres'],
    status: 'published',
    gepubliceerdOp: '2024-03-15T10:00:00Z',
  },
  {
    _id: 'e3', _type: 'event',
    titel: 'Webinar: Eerste resultaten benchmarkonderzoek Informatiebeveiliging',
    slug: 'webinar-benchmark-informatiebeveiliging-2024',
    samenvatting: 'De onderzoekers presenteren de eerste resultaten van het benchmarkonderzoek informatiebeveiliging bij gemeenten en provincies.',
    startdatum: '2024-07-04', starttijd: '10:00', eindtijd: '11:30',
    locatie: 'Online (Zoom)',
    online: true,
    aanmeldUrl: '#',
    themas: [DUMMY_THEMAS[3]], doelgroepen: ['gemeente', 'provincie'],
    tags: ['webinar', 'benchmark', 'informatiebeveiliging'],
    status: 'published',
    gepubliceerdOp: '2024-04-10T10:00:00Z',
  },
]
